simrdatvE <- function(nsnp, N, t, TIME, Lambda, maf, bsnp){
  
  # This function creates a dataframe (dat) with uncorrelated (phe) & correlated   
  # phenotypes (qt) for N inds (id) across t time points (time). They are      
  # generated by modeling snp-by-E interaction, where the snp is of a given maf,   
  # to have an effect bsnp + an error term. Qt is correlated by taking the  
  # inverse of the covariance matrix. The environmental factor (E) is varying  
  # per ind and per time point.
  #   
  # @Para: nsnp (double) is the number of snps being tested, N (double) is the
  # number of unrelated individuals, t (double) is the number of time points,
  # TIME (vector) is the spacing of measurement, Lambda (matrix) is the inverse
  # of the covariance matrix defining the correlation among phenotypes across 
  # time points derived via cholesky decomposition, maf (double) is the 
  # minor allele frequency and bsnp (double) is the snp effect size.
  
  snp = rbinom(N, 2, maf)
  E = matrix(rnorm(N*t, 0, 1), N, t) # this should be a matrix!!! CORRECTED THIS 1/20/25!                                                     
  emat = matrix(rnorm(N*t), N, t) %*% Lambda
  Y0 = snp*0 + snp*E*bsnp + matrix(rnorm(N * t), N, t)
  Y = snp*0 + snp*E*bsnp + emat
  
  dat <<- data.frame(qt = c(Y), phe = c(Y0), snp = rep(snp, times = t), 
                     E = c(E), time = rep(TIME, each = N),  
                     id = as.factor(rep(1:N, times = t)))
  
}