simrdatm <- function(nsnp, N, t, TIME, Lambda, maf, bsnp){
  
  # This function creates a dataframe (dat) with uncorrelated (phe) & correlated   
  # phenotypes (qt) for N inds (id) across t time points (time). They are      
  # generated by modeling snps of a given maf to have an effect bsnp + an error  
  # term. Qt is correlated by taking the inverse of the covariance matrix.
  #   
  # @Para: nsnp (double) is the number of snps being tested, N (double) is the
  # number of unrelated individuals, t (double) is the number of time points,
  # TIME (vector) is the spacing of measurement, Lambda (matrix) is the inverse
  # of the covariance matrix defining the correlation among phenotypes across 
  # time points derived via cholesky decomposition, maf (double) is the 
  # minor allele frequency and bsnp (double) is the snp effect size.
  
  snp = rbinom(N, 2, maf)
  emat = matrix(rnorm(N * t), N, t) %*% Lambda
  Y0 = snp %*% matrix(bsnp, 1, t) + matrix(rnorm(N * t), N, t) 
  Y = snp %*% matrix(bsnp, 1, t) + emat # %*% operator promotes snp vec into a matrix
  
  dat <<- data.frame(qt = c(Y), phe = c(Y0), snp = rep(snp, times = t), 
             time = rep(TIME, each = N), id = as.factor(rep(1:N, times = t)))
  
}