## Read in all dataframes generated by Simtest_bias-loglin.R then run trajGWAS, collect params of interest & calculate bias

using TrajGWAS, CSV, DataFrames, Tables

files = readdir("/Users/ralphp/trajsimdat/loglin/", join=true)
pvals = zeros(length(files),2)
bias = zeros(length(files),5)
simulated = [0 0 0 2*0.1 0.8] # 2*tau since Var(e_ij) = sigma^2 exp(2*tau_snp) 

for i in 1:length(files)
	dat = CSV.read(files[i], DataFrame)
	pvalpath = "/Users/ralphp/pval.txt"
	nullpath = "/Users/ralphp/null.txt"
	trajgwas(@formula(phe~1+time+snp), @formula(phe~1),  @formula(phe~1+snp), :id, dat, pvalfile=pvalpath, nullfile=nullpath)
	res = readlines("null.txt") # saves as an array
	coefs = res[18:22] # retrieves b and tau coefs
	ranint = res[25] # retrieves ranint
	b_int = parse(Float64, coefs[1][18:30])
	b_time =  parse(Float64, coefs[2][18:30])
	b_snp = parse(Float64, coefs[3][18:30])
	tau_snp =  parse(Float64, coefs[5][18:30])
	gamma_j = parse(Float64, ranint[20:length(ranint)])
	p_bsnp = coefs[3][50:length(coefs[3])+1]
	p_tausnp = coefs[5][50:length(coefs[3])+1]

	if contains(p_bsnp, "<")
		p_bsnp = 0.00000000000000000001
	else p_bsnp = parse(Float64, p_bsnp)
	end

	if contains(p_tausnp, "<")
		p_tausnp = 0.00000000000000000001
	else p_tausnp = parse(Float64, p_tausnp)
	end

	est = [b_int b_time b_snp tau_snp gamma_j p_bsnp p_tausnp]
	diff = est[1:5]' - simulated
	bias[i,1:5] = diff
	pvals[i,1:2] = est[6:7]
end

## Bias calculation

files[1] # start of RI 
files[101] # start of RIS
files[201] # start of RIRI

beg = [1 101 201]
last = [100 200 300]
xbars = zeros(3,5)

for i in 1:length(beg)
	mean_beta_int = mean(bias[beg[i]:last[i],1])
	mean_beta_time = mean(bias[beg[i]:last[i],2])
	mean_beta_snp = mean(bias[beg[i]:last[i],3])
	mean_tau_snp = mean(bias[beg[i]:last[i],4])
	mean_gamma_j = mean(bias[beg[i]:last[i],5])
	xbars[i, 1:5] = [mean_beta_int mean_beta_time mean_beta_snp mean_tau_snp mean_gamma_j]
end

## SE calculation

sqdiff = zeros(length(files))
se_beta_int = zeros(3)
for i in 1:length(beg)
	for j in beg[i]:last[i]
		sqdiff[j] = (bias[j] - xbars[i,1])^2
	end
	se_beta_int[i] = sqrt(sum(sqdiff[beg[i]:last[i]]) / last[1])
end

sqdiff = zeros(length(files))
se_beta_time = zeros(3)
for i in 1:length(beg)
	for j in beg[i]:last[i]
		sqdiff[j] = (bias[j] - xbars[i,2])^2
	end
	se_beta_time[i] = sqrt(sum(sqdiff[beg[i]:last[i]]) / last[1])
end

sqdiff = zeros(length(files))
se_beta_snp = zeros(3)
for i in 1:length(beg)
	for j in beg[i]:last[i]
		sqdiff[j] = (bias[j] - xbars[i,3])^2
	end
	se_beta_snp[i] = sqrt(sum(sqdiff[beg[i]:last[i]]) / last[1])
end

sqdiff = zeros(length(files))
se_tau_snp = zeros(3)
for i in 1:length(beg)
	for j in beg[i]:last[i]
		sqdiff[j] = (bias[j] - xbars[i,4])^2
	end
	se_tau_snp[i] = sqrt(sum(sqdiff[beg[i]:last[i]]) / last[1])
end

sqdiff = zeros(length(files))
se_gamma_j = zeros(3)
for i in 1:length(beg)
	for j in beg[i]:last[i]
		sqdiff[j] = (bias[j] - xbars[i,5])^2
	end
	se_gamma_j[i] = sqrt(sum(sqdiff[beg[i]:last[i]]) / last[1])
end

SEs = [se_beta_int se_beta_time se_beta_snp se_tau_snp se_gamma_j]

## Save xbars and SEs

CSV.write("/Users/ralphp/Desktop/AP Genetics/traj_xbars.csv",  Tables.table(xbars), writeheader=false)
CSV.write("/Users/ralphp/Desktop/AP Genetics/traj_SEs.csv",  Tables.table(SEs), writeheader=false)


